name: Sub2Sub VM Migration

on:
  workflow_dispatch:
    inputs:
      phase:
        description: "Phase to execute"
        required: true
        default: "all"
        type: choice
        options:
          - all
          - validate
          - backup
          - prepare
          - move
          - post
          - backupsetup

permissions:
  id-token: write
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Read Config
        run: |
          echo "SOURCE_SUB=$(jq -r .sourceSubscription config/migration-config.json)" >> $GITHUB_ENV
          echo "DEST_SUB=$(jq -r .destinationSubscription config/migration-config.json)" >> $GITHUB_ENV
          echo "RG=$(jq -r .resourceGroup config/migration-config.json)" >> $GITHUB_ENV
          echo "VM=$(jq -r .vmName config/migration-config.json)" >> $GITHUB_ENV
          echo "VAULT=$(jq -r .sourceVaultName config/migration-config.json)" >> $GITHUB_ENV

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ env.SOURCE_SUB }}
          enable-AzPSSession: true

      - name: Install Latest Az Module
        shell: pwsh
        run: |
          Install-Module Az -Repository PSGallery -Force -Scope CurrentUser -AllowClobber
          Import-Module Az -Force
          Get-Module Az | Select Name, Version

      - name: Run Script
        shell: pwsh
        run: |
          ./scripts/main.ps1 `
            -SourceSubscription "$env:SOURCE_SUB" `
            -DestinationSubscription "$env:DEST_SUB" `
            -ResourceGroup "$env:RG" `
            -VMName "$env:VM" `
            -SourceVaultName "$env:VAULT" `
            -Phase "${{ github.event.inputs.phase }}"
